overview:
  title: React
  image: logo.png
  description: Shows how FSI components can be implemented in React.
  order: 10
  facts:
    - Sample component containing FSI ThumbBar
    - FSI Component
sample:
  template:
    schema: react-taupe
    components:
      react:
        theme: data/furniture.yml
        data:
          hero:
            url: /server?type=image&source=images/samples/ssi/furniture/house-6691124.jpg&width=1903&rect=0.01416,0.53388,0.75133,0.21963
            height: 33vh
            logo:
              url: /static/assets/samples/ssi/sale.svg
              height: 30%
            title: Black Friday
            description: Check out our furniture sale.
            link: SHOP NOW
          highlight: REACT OF THE DAY
          credits:
            photos:
              - author: various artists
                link: https://pixabay.com/
                platform: Pixabay
            viewer:
              link: https://www.neptunelabs.com/fsi-viewer/
      fsi:
        viewer: true
        thumbBar: true
      bootstrap:
        icons: true
