title: Simple ThumbBar
image: logo.png
description: This simple demo shows a normal thumb bar with zoom function.
priority: 1
jsfiddle:
  mapping:
    html: "index.html"
    css: "simple.css"
    js: "simple.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/touchzoom/js/fsitouchzoom.js"
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/thumbbar/js/fsithumbbar.js"
