overview:
  title: Product Carousel
  image: logo.png
  description: Shows how a product carousel could look with metadata and buttons used.
  order: 3
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      footer: true
      fsi:
        thumbBar: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    css: "features.css"
    js: "features.js"
jsfiddle:
  deploy: true
